/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 coin.glb 
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, Center, Grid, Resize } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

export default function Glyph(props){
  const ref = useRef()
  const viewport = useThree((state) => state.viewport)
  return(
    <>
      <Center onCentered={({ container, height }) => container.scale.setScalar(viewport.height / (height*2.5))} ref={ref} >
          <Coin {...props}/>
      </Center>
    </>
  )
}

function Coin(props) {
  const { nodes, materials } = useGLTF('/coin.glb')
  const ref = useRef()
  useFrame((state, delta) => {
    if (ref.current) ref.current.rotation.z += 0.001
  })
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes['4-_'].geometry} material={materials.blank_} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['3-_'].geometry} material={materials.blank_} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['2-_'].geometry} material={materials.blank_} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['1-_Denar24085_O_Mater'].geometry} material={materials.Denar24085_O_Mat} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/coin.glb')
